// Code generated by goctl. DO NOT EDIT!
// Source: problem.proto

package server

import (
	"context"

	"queoj/service/problem/internal/logic"
	"queoj/service/problem/internal/svc"
	"queoj/service/problem/problem"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetProblemDetail(ctx context.Context, in *problem.Integer) (*problem.ProblemDetail, error) {
	l := logic.NewGetProblemDetailLogic(ctx, s.svcCtx)
	return l.GetProblemDetail(in)
}

func (s *UserServer) GetAllProblem(ctx context.Context, in *problem.Empty) (*problem.ProblemPage, error) {
	l := logic.NewGetAllProblemLogic(ctx, s.svcCtx)
	return l.GetAllProblem(in)
}

func (s *UserServer) GetProblemIO(ctx context.Context, in *problem.Integer) (*problem.ProblemIO, error) {
	l := logic.NewGetProblemIOLogic(ctx, s.svcCtx)
	return l.GetProblemIO(in)
}

func (s *UserServer) GetProblemsByTags(ctx context.Context, in *problem.ProblemsByTagReq) (*problem.ProblemPage, error) {
	l := logic.NewGetProblemsByTagsLogic(ctx, s.svcCtx)
	return l.GetProblemsByTags(in)
}
