// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"queoj/service/user/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	AddCoinOrPointReq  = user.AddCoinOrPointReq
	ChangePasswordReq  = user.ChangePasswordReq
	ChangeUserInfoReq  = user.ChangeUserInfoReq
	LoginByCodeReq     = user.LoginByCodeReq
	LoginByPasswordReq = user.LoginByPasswordReq
	LoginResult        = user.LoginResult
	RankByUserIdReq    = user.RankByUserIdReq
	RefreshReq         = user.RefreshReq
	Result             = user.Result
	Tokens             = user.Tokens
	UserInfo           = user.UserInfo
	UserInfoReq        = user.UserInfoReq
	UserInfoReqByEmail = user.UserInfoReqByEmail
	UserRank           = user.UserRank

	User interface {
		LoginByPassword(ctx context.Context, in *LoginByPasswordReq) (*LoginResult, error)
		LoginByCode(ctx context.Context, in *LoginByCodeReq) (*LoginResult, error)
		AddCoinOrPoint(ctx context.Context, in *AddCoinOrPointReq) (*Result, error)
		ChangeUserInfo(ctx context.Context, in *ChangeUserInfoReq) (*Result, error)
		ChangePassword(ctx context.Context, in *ChangePasswordReq) (*Result, error)
		GetUserRank(ctx context.Context, in *RankByUserIdReq) (*UserRank, error)
		GetUserInfo(ctx context.Context, in *UserInfoReq) (*UserInfo, error)
		SendVerifyEmail(ctx context.Context, in *UserInfoReqByEmail) (*Result, error)
		RefreshToken(ctx context.Context, in *RefreshReq) (*Tokens, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) LoginByPassword(ctx context.Context, in *LoginByPasswordReq) (*LoginResult, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginByPassword(ctx, in)
}

func (m *defaultUser) LoginByCode(ctx context.Context, in *LoginByCodeReq) (*LoginResult, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginByCode(ctx, in)
}

func (m *defaultUser) AddCoinOrPoint(ctx context.Context, in *AddCoinOrPointReq) (*Result, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddCoinOrPoint(ctx, in)
}

func (m *defaultUser) ChangeUserInfo(ctx context.Context, in *ChangeUserInfoReq) (*Result, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ChangeUserInfo(ctx, in)
}

func (m *defaultUser) ChangePassword(ctx context.Context, in *ChangePasswordReq) (*Result, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ChangePassword(ctx, in)
}

func (m *defaultUser) GetUserRank(ctx context.Context, in *RankByUserIdReq) (*UserRank, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserRank(ctx, in)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *UserInfoReq) (*UserInfo, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in)
}

func (m *defaultUser) SendVerifyEmail(ctx context.Context, in *UserInfoReqByEmail) (*Result, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendVerifyEmail(ctx, in)
}

func (m *defaultUser) RefreshToken(ctx context.Context, in *RefreshReq) (*Tokens, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RefreshToken(ctx, in)
}
