// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"queoj/service/user/internal/logic"
	"queoj/service/user/internal/svc"
	"queoj/service/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) LoginByPassword(ctx context.Context, in *user.LoginByPasswordReq) (*user.LoginResult, error) {
	l := logic.NewLoginByPasswordLogic(ctx, s.svcCtx)
	return l.LoginByPassword(in)
}

func (s *UserServer) LoginByCode(ctx context.Context, in *user.LoginByCodeReq) (*user.LoginResult, error) {
	l := logic.NewLoginByCodeLogic(ctx, s.svcCtx)
	return l.LoginByCode(in)
}

func (s *UserServer) SendVerifyEmail(ctx context.Context, in *user.UserInfoReqByEmail) (*user.Result, error) {
	l := logic.NewSendVerifyEmailLogic(ctx, s.svcCtx)
	return l.SendVerifyEmail(in)
}

func (s *UserServer) RefreshToken(ctx context.Context, in *user.RefreshReq) (*user.Tokens, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *UserServer) AddCoinOrPoint(ctx context.Context, in *user.AddCoinOrPointReq) (*user.Result, error) {
	l := logic.NewAddCoinOrPointLogic(ctx, s.svcCtx)
	return l.AddCoinOrPoint(in)
}

func (s *UserServer) ChangeUserInfo(ctx context.Context, in *user.ChangeUserInfoReq) (*user.Result, error) {
	l := logic.NewChangeUserInfoLogic(ctx, s.svcCtx)
	return l.ChangeUserInfo(in)
}

func (s *UserServer) ChangePassword(ctx context.Context, in *user.ChangePasswordReq) (*user.Result, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *UserServer) RequestPrivilegeEscalation(ctx context.Context, in *user.PrivilegeEscalationReq) (*user.Result, error) {
	l := logic.NewRequestPrivilegeEscalationLogic(ctx, s.svcCtx)
	return l.RequestPrivilegeEscalation(in)
}

func (s *UserServer) ApprovalPEReq(ctx context.Context, in *user.ApprovalPrivilegeEscalationReq) (*user.Result, error) {
	l := logic.NewApprovalPEReqLogic(ctx, s.svcCtx)
	return l.ApprovalPEReq(in)
}

func (s *UserServer) GetAllActivePEReq(ctx context.Context, in *user.Empty) (*user.PEList, error) {
	l := logic.NewGetAllActivePEReqLogic(ctx, s.svcCtx)
	return l.GetAllActivePEReq(in)
}

func (s *UserServer) GetUserRank(ctx context.Context, in *user.RankByUserIdReq) (*user.UserRank, error) {
	l := logic.NewGetUserRankLogic(ctx, s.svcCtx)
	return l.GetUserRank(in)
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.UserInfoReq) (*user.UserInfo, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) GetUserPrivilegeEscalation(ctx context.Context, in *user.RankByUserIdReq) (*user.PrivilegeEscalationDetail, error) {
	l := logic.NewGetUserPrivilegeEscalationLogic(ctx, s.svcCtx)
	return l.GetUserPrivilegeEscalation(in)
}
