// Code generated by goctl. DO NOT EDIT!
// Source: solution.proto

package server

import (
	"context"

	"queoj/service/solution/internal/logic"
	"queoj/service/solution/internal/svc"
	"queoj/service/solution/solution"
)

type SolutionServer struct {
	svcCtx *svc.ServiceContext
}

func NewSolutionServer(svcCtx *svc.ServiceContext) *SolutionServer {
	return &SolutionServer{
		svcCtx: svcCtx,
	}
}

func (s *SolutionServer) GetSolutionDetail(ctx context.Context, in *solution.SolutionByIdReq) (*solution.SolutionDetail, error) {
	l := logic.NewGetSolutionDetailLogic(ctx, s.svcCtx)
	return l.GetSolutionDetail(in)
}

func (s *SolutionServer) GetAllSolutionByPid(ctx context.Context, in *solution.AllSolutionByPidReq) (*solution.SolutionList, error) {
	l := logic.NewGetAllSolutionByPidLogic(ctx, s.svcCtx)
	return l.GetAllSolutionByPid(in)
}

func (s *SolutionServer) AddSolution(ctx context.Context, in *solution.SolutionAddReq) (*solution.Empty, error) {
	l := logic.NewAddSolutionLogic(ctx, s.svcCtx)
	return l.AddSolution(in)
}
