// Code generated by goctl. DO NOT EDIT!
// Source: email.proto

package server

import (
	"context"

	"queoj/service/email/email"
	"queoj/service/email/internal/logic"
	"queoj/service/email/internal/svc"
)

type EmailServer struct {
	svcCtx *svc.ServiceContext
}

func NewEmailServer(svcCtx *svc.ServiceContext) *EmailServer {
	return &EmailServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServer) SendAsync(ctx context.Context, in *email.SendMailReq) (*email.SendMailResp, error) {
	l := logic.NewSendAsyncLogic(ctx, s.svcCtx)
	return l.SendAsync(in)
}

func (s *EmailServer) SendSync(ctx context.Context, in *email.SendMailReq) (*email.SendMailResp, error) {
	l := logic.NewSendSyncLogic(ctx, s.svcCtx)
	return l.SendSync(in)
}
